services:
  s3:
    hostname: airflow-s3
    image: minio/minio:RELEASE.2022-12-12T19-27-27Z
    ports:
      - 9010:9000
      - 9011:9001
    environment:
      - MINIO_ROOT_USER=airflow
      - MINIO_ROOT_PASSWORD=airflowpass
    healthcheck:
      test: [ 'CMD', 'curl', 'http://localhost:9000/minio/health/live' ]
      start_period: 10s
      timeout: 5s
      interval: 3s
      retries: 100
    command: server /data --console-address ":9001"